<?php
namespace App\Http\Repositories\Admin;

use App\Entities\Admin\Sales;
use App\Entities\Admin\SalesItems;
use App\Http\Repositories\BaseRepo;


class SalesRepo extends BaseRepo
{

    public function getModel()
    {
        return new Sales();
    }

    public function create($data)
    {
        $sales = parent::create($data); // TODO: Change the autogenerated stub

        if (!is_null($data->budgets_id))
        {
            $budgetsItemsRepo = new BudgetsItemsRepo();
            $salesItemsRepo = new SalesItemsRepo();
            $itemsRepo = new ItemsRepo();

            $budgetsItems = $budgetsItemsRepo->getModel()->where('budgets_id', $data->budgets_id)->get();


            foreach ($budgetsItems as $budgetItem)
            {
                $budget = $budgetItem->budgets;

                $item = $itemsRepo->asignItem($budgetItem->models_id, $data->branches_confirm_id,$sales->id);

                if($item != false)
                {

                    $new = new SalesItems();
                    $new->sales_id = $sales->id;
                    $new->items_id = $item;
                    $new->price_actual = $budgetItem->price_actual;
                    $new->save();

//                    if($budget->additionables->count() != 0)
//                    {
//
//                        foreach ($budget->additionables as $additionals)
//                        {
//                            $sales->additionables()->create(['additionals_id' => $additionals->additionals_id , 'amount' => $additionals->amount]);
//                        }
//                    };


                }else{

                    return false;
                    //return redirect()->back()->withErrors('El Articulo no se pudo Asignar!');

                }
            }


            $presu = new BudgetsRepo();

            if($presu->find($data->budgets_id)->additionables->count() != 0)
            {

                foreach ($presu->find($data->budgets_id)->additionables as $additionals)
                {
                    $sales->additionables()->create(['additionals_id' => $additionals->additionals_id , 'amount' => $additionals->amount]);
                }
            };

        }

        return $sales;
    }


}