<?php
namespace App\Http\Repositories\Admin;

use App\Entities\Admin\TypesSmallBoxes;
use App\Http\Repositories\BaseRepo;


class TypesSmallBoxesRepo extends BaseRepo {
    
    public function getModel()
    {
        return new TypesSmallBoxes;
    }


    public function create($data)
    {
        $model =  parent::create($data); // TODO: Change the autogenerated stub

        return $model;
    }

    public function update($id, $data)
    {
        $model =  parent::update($id, $data); // TODO: Change the autogenerated stub

        return $model;

    }

    public function destroy($id)
    {
        $model =  parent::destroy($id); // TODO: Change the autogenerated stub

        return $model;

    }

}